[tool.poetry]
name = "winter-arc"
version = "0.1.0"
description = ""
authors = ["rafgonlop1 <rafaelbenzal96@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.39.0"
pandas = "^2.2.3"
plotly = "^5.24.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
